polygon_pos_package:
  participants:
    - kind: validator
      el_type: bor
      cl_type: heimdall-v2
      count: 1
    - kind: rpc
      el_type: bor
      cl_type: heimdall-v2
      count: 1
  network_params:
    # consensus layer
    cl_chain_id: 4928
    # execution layer
    el_chain_id: heimdall-4928
