polygon_pos_package:
  participants:
    - kind: validator
      el_type: bor
      cl_type: heimdall-v2
      count: 4
    - kind: rpc
      el_type: bor
      cl_type: heimdall-v2
      count: 2
    - kind: rpc
      el_type: erigon
      cl_type: heimdall-v2
      count: 2
