polygon_pos_package:
  participants:
    # Bor validator nodes (7 validators, 3 active block producers)
    - kind: validator
      count: 7
      el_bor_produce_witness: true
      cl_type: heimdall-v2
      el_type: bor

    # Bor and erigon RPC nodes (3 rpc nodes, one stateless bor node, one stateful bor node, one stateful erigon node)
    - kind: rpc
      count: 1
      el_bor_sync_with_witness: true
      cl_type: heimdall-v2
      el_type: bor

    - kind: rpc
      count: 1
      el_bor_sync_with_witness: false
      cl_type: heimdall-v2
      el_type: bor
    
    - kind: rpc
      count: 1
      el_bor_sync_with_witness: false
      cl_type: heimdall-v2
      el_type: erigon

    # Bor archive node
    - kind: archive
      count: 1
      cl_type: heimdall-v2
      el_type: bor

  additional_services:
    - observability
    - test_runner
