polygon_pos_package:
  network_params:
    el_block_interval_seconds: 1

  participants:
    # Validator nodes
    - kind: validator
      cl_type: heimdall-v2
      cl_image: local/heimdall-v2:1995663
      el_type: bor
      el_image: local/bor:82899bd
      count: 2
      el_bor_produce_witness: true

    # RPC nodes
    - kind: rpc
      cl_type: heimdall-v2
      cl_image: local/heimdall-v2:1995663
      el_type: bor
      el_image: local/bor:82899bd
      el_bor_produce_witness: true
      el_bor_sync_with_witness: false
      count: 1

    - kind: rpc
      cl_type: heimdall-v2
      cl_image: local/heimdall-v2:1995663
      el_type: bor
      el_image: local/bor:82899bd
      el_bor_produce_witness: true
      el_bor_sync_with_witness: true
      count: 1

    - kind: rpc
      cl_type: heimdall-v2
      cl_image: local/heimdall-v2:1995663
      el_type: bor
      el_image: local/bor:82899bd
      el_bor_produce_witness: false
      el_bor_sync_with_witness: false
      count: 1

  additional_services:
    - prometheus_grafana
    - test_runner
