participants:
  - el_type: geth
    el_image: ethereum/client-go:v1.15.11
    cl_type: lighthouse
    cl_image: ethpandaops/lighthouse:unstable-6135f41
    use_separate_vc: true
    vc_type: lighthouse
    vc_image: ethpandaops/lighthouse:unstable-6135f41
    count: 1

network_params:
  preset: minimal
  seconds_per_slot: 1
  network_id: "3151908"
  prefunded_accounts: '{"0x74Ed6F462Ef4638dc10FFb05af285e8976Fb8DC9": {"balance": "1000000000ETH"}}'
