participants:
  - count: 1
    cl_type: lighthouse
    cl_image: sigp/lighthouse:v8.1.0
    el_type: geth
    el_image: ethereum/client-go:v1.17.0
    use_separate_vc: true
    vc_type: lighthouse
    vc_image: sigp/lighthouse:v8.1.0
    supernode: True

network_params:
  network_id: "3151908"
  prefunded_accounts: '{"0x74Ed6F462Ef4638dc10FFb05af285e8976Fb8DC9": {"balance": "1000000000ETH"}}'
  seconds_per_slot: 1
  preset: minimal
